// Copyright 2002-2011, University of Colorado
/**
 * Resources (images and translated strings) for "SugarAndSaltSolutions" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
define( function( require ) {
  'use strict';

  // modules
  var inherit = require( 'PHET_CORE/inherit' );
  var BufferedImage = require( 'java.awt.image.BufferedImage' );
  var PhetResources = require( 'edu.colorado.phet.common.phetcommon.resources.PhetResources' );

  var PROJECT_NAME = "sugar-and-salt-solutions";
  var RESOURCES = new PhetResources( PROJECT_NAME );

  // static class: Strings
  var Strings =
//Strings
    define( function( require ) {
      var BALL_AND_STICK = RESOURCES.getLocalizedString( "ballAndStick" );
      var CALCIUM = RESOURCES.getLocalizedString( "calcium" );
      var CALCIUM_CHLORIDE_CA_CL_2 = RESOURCES.getLocalizedString( "calciumChlorideCaCl2" );
      var CALCIUM_CHLORIDE_NEW_LINE = RESOURCES.getLocalizedString( "calciumChlorideNewLine" );
      var CHLORIDE = RESOURCES.getLocalizedString( "chloride" );
      var CONCENTRATION = RESOURCES.getLocalizedString( "concentration" );
      var CONDUCTIVITY = RESOURCES.getLocalizedString( "conductivity" );
      var EVAPORATION = RESOURCES.getLocalizedString( "evaporation" );
      var GLUCOSE = RESOURCES.getLocalizedString( "glucose" );
      var GLUCOSE_C_6_H_12_O_6 = RESOURCES.getLocalizedString( "glucoseC6H12O6" );
      var LOADING = RESOURCES.getLocalizedString( "loading" );
      var LOTS = RESOURCES.getLocalizedString( "lots" );
      var MACRO = RESOURCES.getLocalizedString( "macro" );
      var METAL = RESOURCES.getLocalizedString( "metal" );
      var MICRO = RESOURCES.getLocalizedString( "micro" );
      var NITRATE = RESOURCES.getLocalizedString( "nitrate" );
      var NON_METAL = RESOURCES.getLocalizedString( "nonMetal" );
      var NONE = RESOURCES.getLocalizedString( "none" );
      var PATTERN__BEAKER_TICK_LABEL = RESOURCES.getLocalizedString( "pattern.beakerTickLabel" );
      var PATTERN__LITERS_SOLUTION = RESOURCES.getLocalizedString( "pattern.litersSolution" );
      var PATTERN__LITERS_WATER = RESOURCES.getLocalizedString( "pattern.litersWater" );
      var PATTERN__MOLES_PER_LITER = RESOURCES.getLocalizedString( "pattern.molesPerLiter" );
      var PATTERN__MOLES_PER_LITER_MULTILINE = RESOURCES.getLocalizedString( "pattern.molesPerLiterMultiline" );
      var PERIODIC_TABLE = RESOURCES.getLocalizedString( "periodicTable" );
      var REMOVE_SALT = RESOURCES.getLocalizedString( "removeSalt" );
      var REMOVE_SOLUTE = RESOURCES.getLocalizedString( "removeSolute" );
      var REMOVE_SOLUTES = RESOURCES.getLocalizedString( "removeSolutes" );
      var REMOVE_SUGAR = RESOURCES.getLocalizedString( "removeSugar" );
      var SALT = RESOURCES.getLocalizedString( "salt" );
      var SHORT_CIRCUIT = RESOURCES.getLocalizedString( "shortCircuit" );
      var SHOW = RESOURCES.getLocalizedString( "show" );
      var SHOW_VALUES = RESOURCES.getLocalizedString( "showValues" );
      var SODIUM = RESOURCES.getLocalizedString( "sodium" );
      var SODIUM_CHLORIDE_NA_CL = RESOURCES.getLocalizedString( "sodiumChlorideNaCl" );
      var SODIUM_CHLORIDE_NEW_LINE = RESOURCES.getLocalizedString( "sodiumChlorideNewLine" );
      var SODIUM_NITRATE_NA_NO_3 = RESOURCES.getLocalizedString( "sodiumNitrateNaNO3" );
      var SODIUM_NITRATE_NEW_LINE = RESOURCES.getLocalizedString( "sodiumNitrateNewLine" );
      var SOLUTE = RESOURCES.getLocalizedString( "solute" );
      var SPACE_FILL = RESOURCES.getLocalizedString( "spaceFill" );
      var SUCROSE = RESOURCES.getLocalizedString( "sucrose" );
      var SUCROSE_C_12_H_22_O_11 = RESOURCES.getLocalizedString( "sucroseC12H22O11" );
      var SUGAR = RESOURCES.getLocalizedString( "sugar" );
      var SUGAR_HIGHLIGHT = RESOURCES.getLocalizedString( "sugarHighlight" );
      var SUGAR_IN_3_D = RESOURCES.getLocalizedString( "sugarIn3D" );
      var WATER = RESOURCES.getLocalizedString( "water" );
      var WATER_PARTIAL_CHARGES = RESOURCES.getLocalizedString( "waterPartialCharges" );

      return inherit( Object, Strings, {
        },
//statics
        {
          BALL_AND_STICK: BALL_AND_STICK,
          CALCIUM: CALCIUM,
          CALCIUM_CHLORIDE_CA_CL_2: CALCIUM_CHLORIDE_CA_CL_2,
          CALCIUM_CHLORIDE_NEW_LINE: CALCIUM_CHLORIDE_NEW_LINE,
          CHLORIDE: CHLORIDE,
          CONCENTRATION: CONCENTRATION,
          CONDUCTIVITY: CONDUCTIVITY,
          EVAPORATION: EVAPORATION,
          GLUCOSE: GLUCOSE,
          GLUCOSE_C_6_H_12_O_6: GLUCOSE_C_6_H_12_O_6,
          LOADING: LOADING,
          LOTS: LOTS,
          MACRO: MACRO,
          METAL: METAL,
          MICRO: MICRO,
          NITRATE: NITRATE,
          NON_METAL: NON_METAL,
          NONE: NONE,
          PATTERN__BEAKER_TICK_LABEL: PATTERN__BEAKER_TICK_LABEL,
          PATTERN__LITERS_SOLUTION: PATTERN__LITERS_SOLUTION,
          PATTERN__LITERS_WATER: PATTERN__LITERS_WATER,
          PATTERN__MOLES_PER_LITER: PATTERN__MOLES_PER_LITER,
          PATTERN__MOLES_PER_LITER_MULTILINE: PATTERN__MOLES_PER_LITER_MULTILINE,
          PERIODIC_TABLE: PERIODIC_TABLE,
          REMOVE_SALT: REMOVE_SALT,
          REMOVE_SOLUTE: REMOVE_SOLUTE,
          REMOVE_SOLUTES: REMOVE_SOLUTES,
          REMOVE_SUGAR: REMOVE_SUGAR,
          SALT: SALT,
          SHORT_CIRCUIT: SHORT_CIRCUIT,
          SHOW: SHOW,
          SHOW_VALUES: SHOW_VALUES,
          SODIUM: SODIUM,
          SODIUM_CHLORIDE_NA_CL: SODIUM_CHLORIDE_NA_CL,
          SODIUM_CHLORIDE_NEW_LINE: SODIUM_CHLORIDE_NEW_LINE,
          SODIUM_NITRATE_NA_NO_3: SODIUM_NITRATE_NA_NO_3,
          SODIUM_NITRATE_NEW_LINE: SODIUM_NITRATE_NEW_LINE,
          SOLUTE: SOLUTE,
          SPACE_FILL: SPACE_FILL,
          SUCROSE: SUCROSE,
          SUCROSE_C_12_H_22_O_11: SUCROSE_C_12_H_22_O_11,
          SUGAR: SUGAR,
          SUGAR_HIGHLIGHT: SUGAR_HIGHLIGHT,
          SUGAR_IN_3_D: SUGAR_IN_3_D,
          WATER: WATER,
          WATER_PARTIAL_CHARGES: WATER_PARTIAL_CHARGES
        } );
    } );
  ;
  // static class: Images
  var Images =
//Images
    define( function( require ) {
      var SALT_EMPTY = RESOURCES.getImage( "salt_empty.png" );
      var SALT_FULL = RESOURCES.getImage( "salt_full.png" );
      var SALT_MICRO = RESOURCES.getImage( "salt_micro.png" );
      var SUGAR_CLOSED = RESOURCES.getImage( "sugar_closed.png" );
      var SUGAR_EMPTY_CLOSED = RESOURCES.getImage( "sugar_empty_closed.png" );
      var SUGAR_EMPTY_OPEN = RESOURCES.getImage( "sugar_empty_open.png" );
      var SUGAR_MICRO_CLOSED = RESOURCES.getImage( "sugar_micro_closed.png" );
      var SUGAR_MICRO_OPEN = RESOURCES.getImage( "sugar_micro_open.png" );
      var SUGAR_OPEN = RESOURCES.getImage( "sugar_open.png" );

      return inherit( Object, Images, {
        },
//statics
        {
          SALT_EMPTY: SALT_EMPTY,
          SALT_FULL: SALT_FULL,
          SALT_MICRO: SALT_MICRO,
          SUGAR_CLOSED: SUGAR_CLOSED,
          SUGAR_EMPTY_CLOSED: SUGAR_EMPTY_CLOSED,
          SUGAR_EMPTY_OPEN: SUGAR_EMPTY_OPEN,
          SUGAR_MICRO_CLOSED: SUGAR_MICRO_CLOSED,
          SUGAR_MICRO_OPEN: SUGAR_MICRO_OPEN,
          SUGAR_OPEN: SUGAR_OPEN
        } );
    } );
  ;
  return inherit( Object, SugarAndSaltSolutionsResources, {
    },
//statics
    {
      PROJECT_NAME: PROJECT_NAME,
      RESOURCES: RESOURCES
    } );
} );

